EXCLUDED_PKGS = [
    "azure_cli_nspkg",
    "azure_cosmosdb_nspkg",
]

def add_exclude_pkgs_command(excluded_pkgs):
    """Add a sed command that excludes packages from runfiles.

    If there are excluded packages, add extra sed command that excludes packages from runfiles. Otherwise, do nothing.

    Args:
      excluded_pkgs: A list of package names such as azure_cosmosdb_nspkg-2.1.3.
    """
    if excluded_pkgs == []:
        return ""

    #  Change pkg name to format understandable by Bazel
    #  e.g. azure_cosmosdb_nspkg-2.1.3  -> __azure_cosmosdb_nspkg_2_1_3
    excluded_pkgs = ["\"__%s\"" % i.replace("-", "_").replace(".", "_").strip() for i in excluded_pkgs]
    excluded_pkgs = "[%s]" % ",".join(excluded_pkgs)

    #  it is last point in the chain of fetching deps from a sandbox.
    #  So it's the best place to exclude pkgs
    #  GetWindowsPathWithUNCPrefix was generated by bazel
    exclude_pkgs_command = \
        "| sed $'s/" + \
        "  python_path_entries = \\[GetWindowsPathWithUNCPrefix(d) for d in python_path_entries\\]/" + \
        "  python_path_entries = [GetWindowsPathWithUNCPrefix\\(d\\)" + \
        " for d in python_path_entries if not list\\(filter\\(d.endswith, %s\\)\\)]/g'" % excluded_pkgs
    return exclude_pkgs_command
