load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "ufuncs",
    srcs = [
        "__init__.py",
        "logsub.py",
        "s3crypt.py",
    ],
    visibility = ["//visibility:public"],
)
