load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "azure_mailer",
    srcs = [
        "__init__.py",
        "azure_queue_processor.py",
        "deploy.py",
        "function.py",
        "handle.py",
        "sendgrid_delivery.py",
        "utils.py",
    ],
    visibility = ["//visibility:public"],
)
