load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "filters",
    srcs = [
        "__init__.py",
        "config.py",
        "core.py",
        "health.py",
        "iamaccess.py",
        "kms.py",
        "metrics.py",
        "missing.py",
        "multiattr.py",
        "offhours.py",
        "related.py",
        "revisions.py",
        "vpc.py",
    ],
    visibility = ["//visibility:public"],
)
