load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "actions",
    srcs = [
        "__init__.py",
        "autotag.py",
        "core.py",
        "invoke.py",
        "metric.py",
        "network.py",
        "notify.py",
        "policy.py",
        "webhook.py",
    ],
    visibility = ["//visibility:public"],
)
