load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "resource_map",
    srcs = ["resource_map.py"],
    visibility = ["//visibility:public"],
)

py_library(
    name = "resources",
    srcs = [
        "__init__.py",
        "appengine.py",
        "bigquery.py",
        "build.py",
        "cloudbilling.py",
        "compute.py",
        "dataflow.py",
        "deploymentmanager.py",
        "dns.py",
        "function.py",
        "gke.py",
        "iam.py",
        "kms.py",
        "loadbalancer.py",
        "logging.py",
        "mlengine.py",
        "network.py",
        "pubsub.py",
        "resource_map.py",
        "resourcemanager.py",
        "service.py",
        "source.py",
        "spanner.py",
        "sql.py",
        "storage.py",
    ],
    visibility = ["//visibility:public"],
)
