name: Bazel coverage
on: [pull_request]

jobs:
  coverage:
    name: Run
    strategy:
      matrix:
        worker: [c7n, c7n_azure, c7n_gcp, c7n_kube, c7n_mailer]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build -v /tmp/C7N-cov:/tmp/C7N-cov --name baz my-baz
      - name: Install coverage
        run: docker exec -t baz pip3 install coverage
      - name: Execute bazel coverage //tests:first_chunk
        if: matrix.worker == 'c7n'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tests:first_chunk
      - name: Execute bazel coverage //tests:second_chunk
        if: matrix.worker == 'c7n'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tests:second_chunk
      - name: Execute bazel coverage //tools/c7n_azure/tests_azure
        if: matrix.worker == 'c7n_azure'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tools/c7n_azure/tests_azure
      - name: Execute bazel coverage //tools/c7n_gcp/tests
        if: matrix.worker == 'c7n_gcp'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tools/c7n_gcp/tests
      - name: Execute bazel coverage //tools/c7n_kube/tests
        if: matrix.worker == 'c7n_kube'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tools/c7n_kube/tests
      - name: Execute bazel coverage //tools/c7n_mailer/tests
        if: matrix.worker == 'c7n_mailer'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tools/c7n_mailer/tests
      - name: Combine coverage data
        run: |
          docker exec -t baz find /tmp/C7N-cov -type f -name '.coverage*' -exec cp -at /tmp/C7N-cov {} +; \
          docker exec -t baz coverage combine /tmp/C7N-cov/; \
      - name: Generate coverage report for c7n
        if: matrix.worker == 'c7n'
        run: docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --skip-empty --include "*/c7n/*"
      - name: Generate coverage report for c7n_azure
        if: matrix.worker == 'c7n_azure'
        run: docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --skip-empty --include "*/c7n_azure/*"
      - name: Generate coverage report for c7n_gcp
        if: matrix.worker == 'c7n_gcp'
        run: docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --skip-empty --include "*/c7n_gcp/*"
      - name: Generate coverage report for c7n_kube
        if: matrix.worker == 'c7n_kube'
        run: docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --skip-empty --include "*/${{ matrix.worker }}/*"
      - name: Generate coverage report for c7n_mailer
        if: matrix.worker == 'c7n_mailer'
        run: docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --skip-empty --include "*/c7n_mailer/*"
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: HTML coverage report for ${{ matrix.worker }}
          path: /tmp/C7N-cov/htmlcov