name: Bazel build wheels
on: [pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        worker: [c7n_wheel, c7n_azure_wheel, c7n_gcp_wheel, c7n_kube_wheel, c7n_mailer_wheel]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build --name baz my-baz
      - name: Execute bazel build //:${{ matrix.worker }}
        run: |
          docker exec -t baz bazel --output_user_root=/tmp/output_build build ${{ matrix.worker }}
          mkdir /tmp/wheel
          sudo find /tmp/output_build/ -type f -name 'c7n*.whl' -exec cp -n -at /tmp/wheel {} +
      - name: Upload wheel into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.worker }}
          path: /tmp/wheel
      - name: Install ${{ matrix.worker }}
        run: sudo find /tmp/output_build/ -type f -name 'c7n*.whl' -exec docker exec -t baz pip3 install {} +