name: Bazel build docs
on: [pull_request]

jobs:
  build:
    name: Build (c7n_sphinxext)
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build --name baz my-baz
      - name: Execute bazel build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
        run: |
          docker exec -t baz bazel --output_user_root=/tmp/output_build build //tools/c7n_sphinxext/c7n_sphinxext:sphinx_gen
          sudo find /tmp/output_build/ -name 'html' -exec cp -n -at /tmp {} +
      - name: Upload docs into artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Html docs
          path: /tmp/html