name: Bazel coverage
on: [pull_request]

jobs:
  coverage:
    name: Coverage
    strategy:
      matrix:
        worker: [
          { name: 'c7n_first', path: 'tests:first_chunk' },
          { name: 'c7n_second', path: 'tests:second_chunk'},
          { name: 'c7n_azure', path: 'tools/c7n_azure/tests_azure' },
          { name: 'c7n_gcp', path: 'tools/c7n_gcp/tests' },
          { name: 'c7n_kube', path: 'tools/c7n_kube/tests' },
          { name: 'c7n_mailer', path: 'tools/c7n_mailer/tests' },
        ]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build -v /tmp/C7N-cov:/tmp/C7N-cov --name baz my-baz
      - name: Execute bazel coverage //${{ matrix.worker.path }}
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build coverage --test_output=errors //${{ matrix.worker.path }}
      - name: Add coverage data files to zip archive
        run: find /tmp/C7N-cov/ -type f -name '.coverage*' -print | zip ${{ matrix.worker.name }} -@
      - name: Upload zip archive into artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.worker.name }}_cov_data
          path: ${{ matrix.worker.name }}.zip
  report:
    name: Coverage report
    needs: coverage
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build -v /tmp/C7N-cov:/tmp/C7N-cov --name baz my-baz
      - name: Install coverage
        run: docker exec -t baz pip3 install coverage
      - name: Download zip coverage data for c7n_first
        uses: actions/download-artifact@v1
        with:
          name: c7n_first_cov_data
      - name: Download zip coverage data for c7n_second
        uses: actions/download-artifact@v1
        with:
          name: c7n_second_cov_data
      - name: Download zip coverage data for c7n_azure
        uses: actions/download-artifact@v1
        with:
          name: c7n_azure_cov_data
      - name: Download zip coverage data for c7n_gcp
        uses: actions/download-artifact@v1
        with:
          name: c7n_gcp_cov_data
      - name: Download zip coverage data for c7n_kube
        uses: actions/download-artifact@v1
        with:
          name: c7n_kube_cov_data
      - name: Download zip coverage data for c7n_mailer
        uses: actions/download-artifact@v1
        with:
          name: c7n_mailer_cov_data
      - name: Unzip coverage data
        run: |
          unzip c7n_first_cov_data/c7n_first.zip
          unzip c7n_second_cov_data/c7n_second.zip
          unzip c7n_azure_cov_data/c7n_azure.zip
          unzip c7n_gcp_cov_data/c7n_gcp.zip
          unzip c7n_kube_cov_data/c7n_kube.zip
          unzip c7n_mailer_cov_data/c7n_mailer.zip
      - name: Generate coverage report
        run: |
          sudo find tmp/C7N-cov -type f -name '.coverage*' -exec cp -at /tmp/C7N-cov {} +
          docker exec -t -e COVERAGE_FILE=/tmp/C7N-cov/.coverage baz coverage combine /tmp/C7N-cov
          docker exec -t -e COVERAGE_FILE=/tmp/C7N-cov/.coverage baz coverage html -d /tmp/C7N-cov/htmlcov --skip-empty
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: HTML coverage report
          path: /tmp/C7N-cov/htmlcov
      - name: Coverage results
        run: docker exec -t -e COVERAGE_FILE=/tmp/C7N-cov/.coverage baz coverage report --skip-empty