name: Run builds in bazel
on: [pull_request]

jobs:
  build:
    name: Run builds in bazel
    strategy:
      matrix:
        worker: [c7n_wheel, c7n_azure_wheel, c7n_gcp_wheel, c7n_kube_wheel, c7n_mailer_wheel]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build --name baz my-baz
      - name: Execute bazel build //:c7n_wheel
        if: matrix.worker == 'c7n_wheel'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build build c7n_wheel
      - name: Execute bazel build //:c7n_azure_wheel
        if: matrix.worker == 'c7n_azure_wheel'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build build c7n_azure_wheel
      - name: Execute bazel build //:c7n_gcp_wheel
        if: matrix.worker == 'c7n_gcp_wheel'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build build c7n_gcp_wheel
      - name: Execute bazel build //:c7n_kube_wheel
        if: matrix.worker == 'c7n_kube_wheel'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build build c7n_kube_wheel
      - name: Execute bazel build //:c7n_mailer_wheel
        if: matrix.worker == 'c7n_mailer_wheel'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build build c7n_mailer_wheel
