name: Run checks in bazel
on: [pull_request]

jobs:
  build:
    name: Run checks in bazel
    strategy:
      matrix:
        worker: [c7n_gcp_tests]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build --name baz my-baz
      - name: Execute bazel test //tools/c7n_gcp/tests
        if: matrix.worker == 'c7n_gcp_tests'
        run: docker exec -t baz bash -c 'source .github/bazel-test-print-logs.sh //tools/c7n_gcp/tests --output_user_root=/tmp/output_build'
