name: Bazel coverage
on: [pull_request]

jobs:
  coverage:
    name: Coverage
    strategy:
      matrix:
        worker: [c7n_first, c7n_second, c7n_gcp, c7n_kube, c7n_mailer]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install bazel
        run: sudo apt-get install bazel
      - name: Execute bazel coverage //tests:first_chunk
        if: matrix.worker == 'c7n_first'
        run: bazel coverage //tests:first_chunk
      - name: Execute bazel coverage //tests:second_chunk
        if: matrix.worker == 'c7n_second'
        run: bazel coverage //tests:second_chunk
      - name: Execute bazel coverage //tools/c7n_gcp/tests
        if: matrix.worker == 'c7n_gcp'
        run: bazel coverage //tools/c7n_gcp/tests
      - name: Execute bazel coverage //tools/c7n_kube/tests
        if: matrix.worker == 'c7n_kube'
        run: bazel coverage //tools/c7n_kube/tests
      - name: Execute bazel coverage //tools/c7n_mailer/tests
        if: matrix.worker == 'c7n_mailer'
        run: bazel coverage //tools/c7n_mailer/tests
      - name: Add coverage data files to zip archive
        run: find /tmp/C7N-cov/ -type f -name '.coverage*' -print | zip ${{ matrix.worker }} -@
      - name: Upload zip archive into artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.worker }}_cov_data
          path: ${{ matrix.worker }}.zip
  report:
    name: Generate coverage report
    needs: coverage
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install coverage
        run: pip install coverage
      - name: Download zip coverage data for c7n_first
        uses: actions/download-artifact@v1
        with:
          name: c7n_first_cov_data
      - name: Download zip coverage data for c7n_second
        uses: actions/download-artifact@v1
        with:
          name: c7n_second_cov_data
      - name: Download zip coverage data for c7n_azure
        uses: actions/download-artifact@v1
        with:
          name: c7n_azure_cov_data
      - name: Download zip coverage data for c7n_gcp
        uses: actions/download-artifact@v1
        with:
          name: c7n_gcp_cov_data
      - name: Download zip coverage data for c7n_kube
        uses: actions/download-artifact@v1
        with:
          name: c7n_kube_cov_data
      - name: Download zip coverage data for c7n_mailer
        uses: actions/download-artifact@v1
        with:
          name: c7n_mailer_cov_data
      - name: Unzip coverage data files
        run: |
          unzip c7n_first_cov_data/c7n_first.zip
          unzip c7n_second_cov_data/c7n_second.zip
          unzip c7n_azure_cov_data/c7n_azure.zip
          unzip c7n_gcp_cov_data/c7n_gcp.zip
          unzip c7n_kube_cov_data/c7n_kube.zip
          unzip c7n_mailer_cov_data/c7n_mailer.zip
      - name: Generate coverage report
        run: |
          find tmp/C7N-cov -type f -name '.coverage*' -exec cp -at tmp/C7N-cov {} +
          cd tmp/C7N-cov
          coverage combine
          coverage html -d htmlcov --skip-empty
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: HTML coverage report
          path: tmp/C7N-cov/htmlcov