name: Bazel coverage
on: [pull_request]

jobs:
  coverage:
    name: Run
    strategy:
      matrix:
        worker: [c7n_azure, c7n_gcp, c7n_kube, c7n_mailer]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build -v /tmp/C7N-cov:/tmp/C7N-cov --name baz my-baz
      - name: Install coverage
        run: docker exec -t baz pip3 install coverage

      - name: Execute bazel coverage //tools/c7n_azure/tests_azure
        if: matrix.worker == 'c7n_azure'
        run: |
          docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tools/c7n_azure/tests_azure
          docker exec -t baz coverage combine /tmp/C7N-cov/tools.c7n_azure.tests_azure
          docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --include */c7n_azure/* --skip-empty
      - name: Execute bazel coverage //tools/c7n_gcp/tests
        if: matrix.worker == 'c7n_gcp'
        run: |
          docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tools/c7n_gcp/tests
          docker exec -t baz coverage combine /tmp/C7N-cov/tools.c7n_gcp.tests
          docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --include */c7n_gcp/* --skip-empty
      - name: Execute bazel coverage //tools/c7n_kube/tests
        if: matrix.worker == 'c7n_kube'
        run: |
          docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tools/c7n_kube/tests
          docker exec -t baz coverage combine /tmp/C7N-cov/tools.c7n_kube.tests
          docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --include */c7n_kube/* --skip-empty
      - name: Execute bazel coverage //tools/c7n_mailer/tests
        if: matrix.worker == 'c7n_mailer'
        run: |
          docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tools/c7n_mailer/tests
          docker exec -t baz coverage combine /tmp/C7N-cov/tools.c7n_mailer.tests
          docker exec -t baz coverage html -d /tmp/C7N-cov/htmlcov --include */c7n_mailer/* --skip-empty
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: Coverage report for ${{ matrix.worker }}
          path: /tmp/C7N-cov/htmlcov