name: Bazel test
on: [pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        worker: ['tests:first_chunk', 'tests:second_chunk', 'tools/c7n_azure/tests_azure',
                 'tools/c7n_gcp/tests', 'tools/c7n_kube/tests', 'tools/c7n_mailer/tests']
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build --name baz my-baz
      - name: Execute bazel test //${{ matrix.worker }}
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build test --test_output=errors //${{ matrix.worker }}