name: Run checks in bazel
on: [pull_request]

jobs:
  build:
    strategy:
      matrix:
        worker: ['coverage tests-first']
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build a docker image with bazel
        run: docker build -f Docker-bazel-exec -t my-baz .
      - name: Run a container with the image
        run: docker run -dit -v /tmp/output_build:/tmp/output_build -v /tmp/C7N-cov:/tmp/C7N-cov --name baz my-baz
      - name: Execute bazel coverage //tests:first_chunk
        if: matrix.worker == 'coverage tests-first'
        run: docker exec -t baz bazel --output_user_root=/tmp/output_build coverage //tests:test_cloudsearch
      - name: Generate coverage report
        run: |
          docker exec -t baz pip install coverage
          docker exec -t baz find /tmp/C7N-cov -type f -name '.coverage*' -exec cp -at /tmp/C7N-cov {} +; \
          docker exec -t baz coverage combine /tmp/C7N-cov/; \
          docker exec -t baz coverage xml
      - name: Upload coverage report
        uses: actions/upload-artifact@v1
        with:
          name: Coverage report XML
          path: coverage.xml